services:
  node-api:
    build: 
      context: ./api_node
      dockerfile: dockerfile
    env_file:
      - ./api_node/.env
    container_name: node-api
    ports:
      - "3000:3000"
    networks:
      - my-network

  python-post:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: python-post
    networks:
      - my-network
    depends_on:
      - node-api

networks:
  my-network:
    driver: bridge
