FROM python:3.9-slim

RUN apt-get update && apt-get install -y cron curl

RUN pip install beautifulsoup4 requests

COPY scraping.sh /project-directory/scraping.sh
COPY clean_data.py /project-directory/clean_data.py
COPY crontab /etc/cron.d/crontab

RUN chmod +x /project-directory/scraping.sh

RUN crontab /etc/cron.d/crontab && chmod 0644 /etc/cron.d/crontab

WORKDIR /project-directory

CMD ["cron", "-f"]
